tagmanager: GTM-WPDQFCR
ga: UA-64073239-3
dominio: https://partidodigital.org.uy/
acceso_url: https://partidodigital.auth0.com/login?client=3yqAXfyeQCu5RcrgSQUsb0M4ojdvif4N
firmas: 1010

plugins:
  - jekyll-sitemap

exclude: [CNAME, README.md, Gemfile, Gemfile.lock]

sass:
  style: compressed
  sass_dir: ./assets/styles
  
collections:
  documentos:
    output: true
  
defaults:
  - scope:
      path: ""
      type: documentos
    values:
      layout: pagina
