tagmanager: GTM-WPDQFCR
dominio: https://partidodigital.org.uy/
email_contacto: hola@partidodigital.org.uy
acceso_url: https://partidodigital.auth0.com/login?client=3yqAXfyeQCu5RcrgSQUsb0M4ojdvif4N

sass:
  style: compressed
  sass_dir: ./assets/styles
  
collections:
  documentos:
    output: true
  
defaults:
  - scope:
      path: ""
      type: documentos
    values:
      layout: pagina
