analytics: UA-64073239-3
dominio: https://partidodigital.org.uy/
email_contacto: hola@partidodigital.org.uy
acceso_url: https://partidodigital.auth0.com/login?client=3yqAXfyeQCu5RcrgSQUsb0M4ojdvif4N
pixel_id: 1560124247567378
google_conversion_id: 949657565
twitter_pixel_id: nwatz

cta:
  nombre: Registrate
  link: https://partidodigital.auth0.com/login?client=3yqAXfyeQCu5RcrgSQUsb0M4ojdvif4N

sass:
  style: compressed
  sass_dir: ./assets/styles
  
collections:
  documentos:
    output: true
  
defaults:
  - scope:
      path: ""
      type: documentos
    values:
      layout: pagina
